### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by aubertc** [knoxrm/OcamlCompiler#1]
First thing first: you see the same error message as me, correct?

```
Error: Dependency cycle between:
   library "lexer" in _build/default/lib
-> required by alias default
File "bin/dune", line 4, characters 12-16:
4 |  (libraries base))
                ^^^^
Error: Library "base" not found.
-> required by _build/default/bin/main.exe
-> required by alias bin/all
-> required by alias default
```

**Comment by aubertc** [comment]
That's actually _two_ errors, and not just one. Did you get a "hello world" project to compile first? Was this project compiling at some point in time? If yes, how did you do it? Can you get back to that state?

**Comment by knoxrm** [comment]
The base library error is not there on my side. Just to check, did you run `opam install base` to install it? 

The project isn't compiling at all. The circular dependency is the error that show up. I have trying multiple things but I haven't been able to figure it out.

**Comment by aubertc** [comment]
Ok, thanks, after install `base` I indeed get only one error message,

```
Error: Dependency cycle between:
   library "lexer" in _build/default/lib
-> required by alias default
```

Please, let me know about the other questions:

> Did you get a "hello world" project to compile first? Was this project compiling at some point in time? If yes, how did you do it? Can you get back to that state?

**Comment by aubertc** [comment]
(And, just to be clear: I understand that this project isn't compiling at all. My questions are "Did it ever compile?", and "Did you ever get any project that you wrote to compile?").

**Comment by knoxrm** [comment]
I was able to compile some older projects I had. Just to check dune was working properly. I think it has to be something wrong with dune  config files that is producing the errors.

**Comment by aubertc** [comment]
Honestly, I would recommend re-starting a different project from scratch, and making very small steps to understand what went wrong. As of now, I can't really retrace your steps to understand where this cycle is coming from. 

Can you start from a simple hello world of some kind, and then build your lexer _very_ progressively?

**Comment by knoxrm** [comment]
I'll try doing that and then I'll report back.

**Comment by aubertc** [comment]
Sorry, but after years of teaching (and practicing) programming, I often find that it's the best strategy: get back to the latest stage where your work compiled. I'm sorry if it means restarting from scratch.

**Comment by knoxrm** [comment]
The circular dependancy issue was fixed in newest commit. Can you please check if it is working on your end?

**Comment by aubertc** [comment]
I have another error message on this machine (about dune being too old) -- this will take me a bit to test it.

**Comment by knoxrm** [comment]
On running `dune --version` I get 3.15.3. Is it the same for you?

**Comment by aubertc** [comment]
Yes, that seems to be solved. Were you able to figure out the exact mistake you were making?
